### ISSUE TITLE
Bug: ArgumentNullException on CallExtensionMethodAsExtensionAnalyzer (CC0026)

### ISSUE THREAD

**Issue by giggio** [code-cracker/code-cracker#810]
This will cause a `ArgumentNullException` in `CallExtensionMethodAsExtensionAnalyzer`, because the method `M` is supposed to have arguments.

````csharp
    class Foo
    {
        public static void N()
        {
            Exts.M();
        }
    }
    static class Exts
    {
        public static void M(this string s) => s.ToString();
    }
````

This is the full error output:

````
Analyzer 'CodeCracker.CSharp.Usage.CallExtensionMethodAsExtensionAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: expression'.	ConsoleApplication4		1	1	IntelliSense	Active	Analyzer 'CodeCracker.CSharp.Usage.CallExtensionMethodAsExtensionAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: ConsoleApplication4
SyntaxTree: C:\p\rabiscos\ConsoleApplication4\ConsoleApplication4\Program.cs
SyntaxNode: Exts.M() [InvocationExpressionSyntax]@[288..296) (20,8)-(20,16)

System.ArgumentNullException: Value cannot be null.
Parameter name: expression
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.MemberAccessExpression(SyntaxKind kind, ExpressionSyntax expression, SyntaxToken operatorToken, SimpleNameSyntax name)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.MemberAccessExpression(SyntaxKind kind, ExpressionSyntax expression, SimpleNameSyntax name)
   at CodeCracker.CSharp.Usage.CallExtensionMethodAsExtensionAnalyzer.CreateInvocationExpression(ExpressionSyntax sourceExpression, SimpleNameSyntax methodName, ArgumentListSyntax argumentList) in C:\p\code-cracker\src\CSharp\CodeCracker\Usage\CallExtensionMethodAsExtensionAnalyzer.cs:line 106
   at CodeCracker.CSharp.Usage.CallExtensionMethodAsExtensionAnalyzer.IsSelectingADifferentMethod(IEnumerable`1 childNodes, SimpleNameSyntax methodName, SyntaxTree tree, IMethodSymbol methodSymbol, ExpressionSyntax invocationExpression, Compilation compilation) in C:\p\code-cracker\src\CSharp\CodeCracker\Usage\CallExtensionMethodAsExtensionAnalyzer.cs:line 63
   at CodeCracker.CSharp.Usage.CallExtensionMethodAsExtensionAnalyzer.AnalyzeInvocation(SyntaxNodeAnalysisContext context, Compilation compilation) in C:\p\code-cracker\src\CSharp\CodeCracker\Usage\CallExtensionMethodAsExtensionAnalyzer.cs:line 54
   at CodeCracker.CSharp.Usage.CallExtensionMethodAsExtensionAnalyzer.<>c__DisplayClass7_0.<AnalyzeCompilation>b__0(SyntaxNodeAnalysisContext context) in C:\p\code-cracker\src\CSharp\CodeCracker\Usage\CallExtensionMethodAsExtensionAnalyzer.cs:line 36
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
````

The PR should pull into the `v1.0.x` branch.

**Comment by giggio** [comment]
Closed on #816
