### ISSUE TITLE
'UnusedParametersCodeFixProvider' encountered an error and has been disabled.

### ISSUE THREAD

**Issue by lgp1985** [code-cracker/code-cracker#913]
#New analyzer:

This method is failing to preview.

Before:
You can add more information here, e.g. conditions under which a diagnostic should not trigger, etc.

Diagnostic Id: `CC0057` (take a number and update the [wiki](https://github.com/code-cracker/code-cracker/wiki/DiagnosticIds))
Category: `<Refactoring>` (see [supported categories](https://github.com/code-cracker/code-cracker/blob/master/src/Common/CodeCracker.Common/SupportedCategories.cs) and their [descriptions](https://github.com/code-cracker/code-cracker/issues/97))
Severity: `Error` (see the [descriptions](https://github.com/code-cracker/code-cracker/#severity-levels))

#Bug

When trying to display the fix (with right mouse click on the specified code) it fails to render, and Visual Studio display the message: **'UnusedParametersCodeFixProvider' encountered an error and has been disabled.**

System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.RemoveAt(Int32 index)
   at async CodeCracker.CSharp.Usage.UnusedParametersCodeFixProvider.RemoveParameterAsync(<Unknown Parameters>)
   at async CodeCracker.CSharp.Usage.UnusedParametersCodeFixProvider.RemoveParameterAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

Current input:

````csharp

        [Obsolete]
        protected int getEnv(string host = "")
        {
            return (int)_getEnv();
        }
````

Expected output after fix applied (if it is a code fix bug):

````csharp

        [Obsolete]
        protected int getEnv()        {
            return (int)_getEnv();
        }
````

**Comment by giggio** [comment]
I can't repro it. Maybe it is already fixed on our released version, or on dev.
If you still see it happening with the latest release (`1.0.3`), try the dev version (from MyGet).

![image](https://user-images.githubusercontent.com/334958/27087547-ae05f998-502b-11e7-9eca-c3be51f1f218.png)
