### ISSUE TITLE
Bug CC0043 ChangeAnyToAll exception on non-LINQ methods

### ISSUE THREAD

**Issue by KristianWedberg** [code-cracker/code-cracker#924]
# Bug

CC0043 "ChangeAnyToAll" throws an exception with user created (i.e. non-LINQ) `Any()` and `All()` methods with v1.0.3.

This code:

````csharp
    class TypeName
    {
        private TypeName xs;

        void Foo() => xs.All();

        public void All()
        {
        }
    }
````

Throws the following exception:

````csharp
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'CodeCracker.CSharp.Refactoring.ChangeAnyToAllAnalyzer' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values.
Parameter name: index'.	CCBug		1	Active	Analyzer 'CodeCracker.CSharp.Refactoring.ChangeAnyToAllAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: CCBug
SyntaxTree: C:\Users\Administrator\documents\visual studio 2017\Projects\CCBug\Program.cs
SyntaxNode: xs.All() [InvocationExpressionSyntax]@[234..242) (12,23)-(12,31)

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.get_Item(Int32 index)
   at CodeCracker.CSharp.Refactoring.ChangeAnyToAllAnalyzer.IsLambdaWithoutBody(InvocationExpressionSyntax invocation)
   at CodeCracker.CSharp.Refactoring.ChangeAnyToAllAnalyzer.GetCorrespondingDiagnostic(SemanticModel semanticModel, InvocationExpressionSyntax invocation)
   at CodeCracker.CSharp.Refactoring.ChangeAnyToAllAnalyzer.AnalyzeInvocation(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
````

The same exception happens if my method is called `Any()`.

At a guess (haven't checked the source code), CC0043 assumes `Any()` and `All()` are LINQ methods, and throws when my user `Any()` and `All()` takes unexpected parameters (in this case void.)

**Comment by carloscds** [comment]
@KristianWedberg I can´t reproduce error with this code. Can you check and send again ?

**Comment by KristianWedberg** [comment]
The bug also needed a `params` parameter, now added above - can you please check again?

**Comment by carloscds** [comment]
@KristianWedberg Bug confirmed!
