### ISSUE TITLE
TernaryOperatorWithAssignmentCodeFixProvider Crashes with Specific If-Else-If-Else Formatting

### ISSUE THREAD

**Issue by TheFanatr** [code-cracker/code-cracker#968]
# TernaryOperatorWithAssignmentCodeFixProvider Crashes with Specific If-Else-If-Else Formatting 
> Bug

### Description
Certain if-else-if-else code formatting causes `TernaryOperatorWithAssignmentCodeFixProvider` to crash upon fix attempt.

#### Input
````csharp
object output = null, sampleObject = null;
Dictionary<string, string> dictionary = null;
if (sampleObject != null && dictionary != null)
{
    output = from m in dictionary select m.Key;
}
else if (dictionary != null)
{
    output = dictionary;
}
else
{
    output = Enumerable.Empty<string>();
}
````

#### Expected Output
````csharp
object output = null, sampleObject = null;
Dictionary<string, string> dictionary = null;
output = sampleObject != null && dictionary != null ? (from m in dictionary select m.Key) : (dictionary != null ? dictionary : (object)Enumerable.Empty<string>());
````
or just a replacement for the else-if-else formatting with the use of a turnary operator.

#### Recieved Output
`TernaryOperatorWithAssignmentCodeFixProvider` has encountered an error and has been disabled.

#### Stack Trace
`System.NullReferenceException : Object reference not set to an instance of an object.
   at CodeCracker.CSharp.Style.TernaryOperatorCodeFixHelper.CastToBaseType(ExpressionSyntax ifExpression,ITypeSymbol ifType,ITypeSymbol elseType,ExpressionSyntax trueExpression)
   at CodeCracker.CSharp.Style.TernaryOperatorCodeFixHelper.CreateExpressions(ExpressionSyntax ifExpression,ExpressionSyntax elseExpression,ITypeSymbol ifType,ITypeSymbol elseType,ITypeSymbol ifConvertedType,ITypeSymbol elseConvertedType,TypeSyntax typeSyntax,SemanticModel semanticModel,ExpressionSyntax& trueExpression,ExpressionSyntax& falseExpression)
   at CodeCracker.CSharp.Style.TernaryOperatorCodeFixHelper.CreateExpressions(ExpressionSyntax ifExpression,ExpressionSyntax elseExpression,SemanticModel semanticModel,ExpressionSyntax& trueExpression,ExpressionSyntax& falseExpression)
   at async CodeCracker.CSharp.Style.TernaryOperatorWithAssignmentCodeFixProvider.MakeTernaryAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)`
#### Environment
**Visual Studio Version**: `15.6.4`
**Target .NET Framework Version**: `4.7.1`
**C# Language Version**: `7.1`

**Comment by giggio** [comment]
I just ran CodeCracker on the latest `master` branch and got not error. Here is the end result:

````csharp
output = sampleObject != null && dictionary != null ? (object)from m in dictionary select m.Key : dictionary != null ? (object)dictionary : Enumerable.Empty<string>();
````

I had to run it twice, first on the second `if`, then on the first. I get not diagnostic on the first until I run it on the second.

Tested on update 7 of VS 2017.

We are about to release an update that should carry the already fixed branch forward.
