### ISSUE TITLE
The latest version does not support SonarQube 7.3

### ISSUE THREAD

**Issue by JohannBlais** [code-cracker/code-cracker#994]
Hello,

The plugin does not load on SonarQube developer 7.3 hosted on Windows Server.
Here is the error message in the web.log

java.lang.IllegalStateException: Fail to instantiate class [org.sonar.plugins.roslynsdk.RoslynSdkGeneratedPlugin] of plugin [codecrackercsharp]
	at org.sonar.core.platform.PluginLoader.instantiatePluginClasses(PluginLoader.java:134)
	at org.sonar.core.platform.PluginLoader.load(PluginLoader.java:66)
	at org.sonar.server.plugins.ServerPluginRepository.loadInstances(ServerPluginRepository.java:267)
	at org.sonar.server.plugins.ServerPluginRepository.start(ServerPluginRepository.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevel2.start(PlatformLevel2.java:110)
	at org.sonar.server.platform.Platform.start(Platform.java:211)
	at org.sonar.server.platform.Platform.startLevel2Container(Platform.java:177)
	at org.sonar.server.platform.Platform.init(Platform.java:87)
	at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:45)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/ServerExtension
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at org.sonar.plugins.roslynsdk.RoslynSdkGeneratedPlugin.<clinit>(RoslynSdkGeneratedPlugin.java:28)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.sonar.core.platform.PluginLoader.instantiatePluginClasses(PluginLoader.java:129)
	... 32 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.ServerExtension
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 52 common frames omitted

Kind regards

**Comment by jjferreira** [comment]
When will this be fixed?  Kind Regards

**Comment by carloscds** [comment]
@jjferreira I will work in this.

**Comment by jjferreira** [comment]
Hi @carloscds when do you think you will have an update on this wonder bit of code.

Thank you in advance.

**Comment by doodz** [comment]
@carloscds 👍  do not forget community Edition ;), we can't update manually.
best regards

**Comment by carloscds** [comment]
@doodz After Microsoft Iginite, I will do this!

**Comment by jjferreira** [comment]
Hi @carloscds  any news on this compability issue?  I'm a .Net developer by trade if I can be of help.  Really would like to use this little bit of code on my new pipeline.  Thank you in advance.

**Comment by carloscds** [comment]
@jjferreira After, Ignite, remember ?

**Comment by carloscds** [comment]
@jjferreira Sorry about this delay, I'm talking with SonarQube but to update CodeCracker I need to create a new version of component here. We are doing this.

**Comment by jjferreira** [comment]
Hi @carloscds any update on this.

Kind Regards

p.s  Muito Obrigado

**Comment by carloscds** [comment]
@jjferreira I'm waiting @giggio generate a new version to update Sonar.

**Comment by jjferreira** [comment]
Hi @giggio any ideia when you creating a new version?

Kind Regards

**Comment by jjferreira** [comment]
@giggio @carloscds 

Any news on the next release?  Would be nice to see it working again on sonarqube.

**Comment by fdvieira** [comment]
any news on this? trying to update to SonarQube version 7.6 but still got this issue.

**Comment by carloscds** [comment]
@giggio Did you generate version ?
